Section "Device"
    Identifier  "Intel"
    Driver      "modesetting"
    Option      "TearFree"   "true"
    Option      "AccelMethod" "glamor"
EndSection

Section "Monitor"
    Identifier  "eDP-1"
    Option      "PreferredMode" "1600x900"
EndSection

Section "Screen"
    Identifier  "DefaultScreen"
    Monitor     "eDP-1"
    Device      "Intel"
EndSection
