-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- Restore cursor shape on exit
-- vim.api.nvim_create_autocmd("VimLeave", {
--   pattern = "*",
--   callback = function()
--     vim.opt.guicursor = ""
--     vim.cmd([[set guicursor=a:ver25]])
--     -- Force terminal to reset cursor
--     io.write("\027[6 q")
--     io.flush()
--   end,
-- })
